### GET request to example server
GET http://localhost:8080

###
GET  http://localhost:8080/api/v1/EmployeeDetails

###
POST  http://localhost:8080/api/v1/EmployeeDetails
Content-Type: application/json

{
  "Name" : "Vivek D",
  "TechStack": "Selenium, Postman, Java"
}
