### GET request to example server
GET http://localhost:8080

###
GET  http://localhost:8080/api/v1/EmployeeDetails

###
GET  http://localhost:8080/api/v1/EmployeeDetails/2
###
POST  http://localhost:8080/api/v1/EmployeeDetails
Content-Type: application/json

{
  "name" : "Vatsal D",
  "techStack": "AI, ML, DS"
}
